Controllers/MailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Mvc;
using MimeKit;

namespace KlassyCafePostgreSql.Controllers
{
    public class MailController : Controller
    {
        public IActionResult Send(string receiverName, string receiverMail, string subject, string body)
        {
            var mailNickname="Klassy Cafe";
            var mailName="Mail Adresiniz";
            var mailPassword="Mail Şifreniz";
            var mailHost="smtp.office365.com";
            var mailPort=587;
            var mailSsl=false;


            MimeMessage mimeMessage = new MimeMessage();
            MailboxAddress mailboxSenderAddress = new MailboxAddress(mailNickname, mailName);
            mimeMessage.From.Add(mailboxSenderAddress);
            MailboxAddress mailboxReceiverAddress = new MailboxAddress(receiverName, receiverMail);
            mimeMessage.To.Add(mailboxReceiverAddress);
            mimeMessage.Subject = subject;
            var bodyBuilder = new BodyBuilder();
            bodyBuilder.HtmlBody = body;
            mimeMessage.Body = bodyBuilder.ToMessageBody();
            SmtpClient smtpClient = new SmtpClient();

            try
            { 
                smtpClient.Connect(mailHost, mailPort, mailSsl);
                smtpClient.Authenticate(mailName, mailPassword);
                var sonuc = smtpClient.Send(mimeMessage);
                smtpClient.Disconnect(true);
                TempData["icon"] = "success";
                TempData["text"] = "Mail Gönderildi.";
                return RedirectToAction("List", "Reservation");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Mail gönderme işlemi başarısız oldu: " + ex.Message);
                return RedirectToAction("List", "Reservation");
            }
            
        }
    }
}

Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KlassyCafePostgreSql.Dtos.ReservationDtos;
using KlassyCafePostgreSql.Services.ReservationServices;
using Microsoft.AspNetCore.Mvc;

namespace KlassyCafePostgreSql.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationService _reservationService;

        public ReservationController(IReservationService reservationService)
        {
            _reservationService = reservationService;
        }

        public async Task<IActionResult> List()
        {
            ViewBag.reservation = "active";

            var values = await _reservationService.GetAllReservationAsync();
            return View(values);
        }

        public IActionResult Create()
        {
            ViewBag.reservation = "active";

            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(CreateReservationDto createReservationDto)
        {
            ViewBag.reservation = "active";

            await _reservationService.CreateReservationAsync(createReservationDto);
            return RedirectToAction("List", "Reservation");
        }

        [HttpPost]
        public async Task<IActionResult> CreateHome(CreateReservationDto createReservationDto)
        {
            await _reservationService.CreateReservationAsync(createReservationDto);
            return Json("Success");
        }

        public async Task<IActionResult> Update(int id)
        {
            ViewBag.reservation = "active";

            var value = await _reservationService.GetByIdReservationAsync(id);
            return View(value);
        }
        
        [HttpPost]
        public async Task<IActionResult> Update(UpdateReservationDto updateReservationDto)
        {
            ViewBag.reservation = "active";

            await _reservationService.UpdateReservationAsync(updateReservationDto);
            return RedirectToAction("List", "Reservation");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _reservationService.DeleteReservationAsync(id);
            return RedirectToAction("List", "Reservation");
        }
    }
}

ViewComponents/Reservation/ReservationViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace KlassyCafePostgreSql.ViewComponents.Reservation
{
    public class ReservationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }  
    }
}

Views/Reservation/Create.cshtml
@model CreateReservationDto
@{
    ViewData["Title"] = "Create";
    Layout = "_LayoutAdmin";
}

<div class="p-5 w-100">
    <div class="container">
        <h5 class="text-center">Reservasyon Ekle</h5>
        <hr>
        <form asp-controller="Reservation" asp-action="Create" method="post">
            <div class="mb-3">
                <label for="ReservationFullname" class="form-label">Ad Soyad</label>
                <input type="text" class="form-control" asp-for="ReservationFullname" id="ReservationFullname">
            </div>
            <div class="mb-3">
                <label for="ReservationEmail" class="form-label">Email</label>
                <input type="text" class="form-control" asp-for="ReservationEmail" id="ReservationEmail">
            </div>
            <div class="mb-3">
                <label for="ReservationPhone" class="form-label">Telefon Numarası</label>
                <input type="text" class="form-control" asp-for="ReservationPhone" id="ReservationPhone">
            </div>
            <div class="mb-3">
                <label for="ReservationPerson" class="form-label">Kişi</label>
                <input type="text" class="form-control" asp-for="ReservationPerson" id="ReservationPerson">
            </div>
            <div class="mb-3">
                <label for="ReservationDate" class="form-label">Tarih</label>
                <input type="text" class="form-control" asp-for="ReservationDate" id="ReservationDate">
            </div>
            <div class="mb-3">
                <label for="ReservationTime" class="form-label">Saat</label>
                <input type="text" class="form-control" asp-for="ReservationTime" id="ReservationTime">
            </div>
            <div class="mb-3">
                <label for="ReservationBody" class="form-label">Mesaj</label>
                <input type="text" class="form-control" asp-for="ReservationBody" id="ReservationBody">
            </div>
            <hr>
            <button type="submit" class="btn btn-success">Kaydet</button>
            <a asp-controller="Reservation" asp-action="List" class="btn btn-dark">Geri</a>
        </form>
    </div>
</div>

Views/Reservation/List.cshtml
@model List<ResultReservationDto>
@{
    ViewData["Title"] = "List";
    Layout = "_LayoutAdmin";
}

<div class="p-5 w-100">
    <div class="container">
        <h5 class="text-center">Reservasyon Listesi</h5>
        <hr>
        @if (Model.Any())
        {
            <table class="table table-bordered table-hover">
                <thead>
                    <tr class="bg-dark text-light">
                        <th scope="col">Tarih & Saat</th>
                        <th scope="col">Ad Soyad</th>
                        <th scope="col">Kişi</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ReservationDate @item.ReservationTime</td>
                            <td>@item.ReservationFullname</td>
                            <td>@item.ReservationPerson</td>
                            <td><button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#staticBackdrop@(item.ReservationId)">Mail Gönder</button></td>
                            <td><a asp-controller="Reservation" asp-action="Update" asp-route-id="@item.ReservationId" class="btn btn-primary">Güncelle</a></td>
                            <td><a asp-controller="Reservation" asp-action="Delete" asp-route-id="@item.ReservationId" class="btn btn-danger">Sil</a></td>
                        </tr>
                        <!-- Modal -->
                        <div class="modal fade" id="staticBackdrop@(item.ReservationId)" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content p-3">
                                    <form asp-controller="Mail" asp-action="Send" method="post">
                                        <div class="mb-3">
                                            <label for="receiverName" class="form-label">Alıcı Ad Soyad</label>
                                            <input type="text" name="receiverName" class="form-control" id="receiverName" value="@item.ReservationFullname">
                                        </div>
                                        <div class="mb-3">
                                            <label for="receiverMail" class="form-label">Alıcı Mail</label>
                                            <input type="text" name="receiverMail" class="form-control" id="receiverMail" value="@item.ReservationEmail">
                                        </div>
                                        <div class="mb-3">
                                            <label for="subject" class="form-label">Konu</label>
                                            <input type="text" name="subject" class="form-control" id="subject">
                                        </div>
                                        <div class="mb-3">
                                            <label for="body" class="form-label">Mesaj</label>
                                            <input type="text" name="body" class="form-control" id="body">
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                                            <button type="submit" class="btn btn-primary">Gönder</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    }
                </tbody>
            </table>
        } else
        {
            <div class="alert alert-primary" role="alert">
                Burası boş. Yeni bir öge ekleyin.
            </div>
        }
        <hr>
        <a asp-controller="Reservation" asp-action="Create" class="btn btn-success">Ekle</a>
    </div>
</div>

@section Scripts
{
    <script src="/signalr/dist/browser/signalr.js"></script>
    <script src="/signalr/dist/browser/signalr.min.js"></script>
    <script>
        var connection = new signalR.HubConnectionBuilder().withUrl("/signalrhub").build();
        connection.start().then(() => {
            connection.invoke("ReservationCount");
        }).catch((err) => { console.log(err) });
    </script>
}

Views/Reservation/Update.cshtml
@model GetByIdReservationDto
@{
    ViewData["Title"] = "Update";
    Layout = "_LayoutAdmin";
}

<div class="p-5 w-100">
    <div class="container">
        <h5 class="text-center">Reservasyon Güncelle</h5>
        <hr>
        <form asp-controller="Reservation" asp-action="Update" method="post">
            <input type="hidden" asp-for="ReservationId">
            <div class="mb-3">
                <label for="ReservationFullname" class="form-label">Ad Soyad</label>
                <input type="text" class="form-control" asp-for="ReservationFullname" id="ReservationFullname">
            </div>
            <div class="mb-3">
                <label for="ReservationEmail" class="form-label">Email</label>
                <input type="text" class="form-control" asp-for="ReservationEmail" id="ReservationEmail">
            </div>
            <div class="mb-3">
                <label for="ReservationPhone" class="form-label">Telefon Numarası</label>
                <input type="text" class="form-control" asp-for="ReservationPhone" id="ReservationPhone">
            </div>
            <div class="mb-3">
                <label for="ReservationPerson" class="form-label">Kişi</label>
                <input type="text" class="form-control" asp-for="ReservationPerson" id="ReservationPerson">
            </div>
            <div class="mb-3">
                <label for="ReservationDate" class="form-label">Tarih</label>
                <input type="text" class="form-control" asp-for="ReservationDate" id="ReservationDate">
            </div>
            <div class="mb-3">
                <label for="ReservationTime" class="form-label">Saat</label>
                <input type="text" class="form-control" asp-for="ReservationTime" id="ReservationTime">
            </div>
            <div class="mb-3">
                <label for="ReservationBody" class="form-label">Mesaj</label>
                <input type="text" class="form-control" asp-for="ReservationBody" id="ReservationBody">
            </div>
            <hr>
            <button type="submit" class="btn btn-primary">Kaydet</button>
            <a asp-controller="Reservation" asp-action="List" class="btn btn-dark">Geri</a>
        </form>
    </div>
</div>